Controle de Fluxo
jpaulohe4rt/c4noobs pull request #32
Opened 2022-10-14 16:09 UTC by vbasilioo

> Alterações solicitadas já foram realizadas. 
@FerroEduardo

2022-10-15 00:35 UTC, FerroEduardo requested changes

2022-10-15 00:35 UTC, FerroEduardo commented on README.MD
> +09. [Estruturas de Decisão](/src/3-Basico/09-EstruturasDeDecisao.md)
1. Nome do arquivo é diferente/link não funciona
    - Remove acentuação e espaçamento, pode usar `-` como espaço tb
2. Apesar de realmente serem estruturas de decisão, esse nome não é muito usado. Eu trocaria para `Controle de Fluxo`

2022-10-15 00:35 UTC, FerroEduardo commented on src/3-Basico/09-Estruturas de Decisões.md
> +    <img src="https://i.imgur.com/3fRO9ah.png">
Sobre todas as imagens de saída, imagino que ficaria melhor para mobile se fossem em texto.  
Talvez algo assim:  

Saída:
```
hello world
```

2022-10-15 00:35 UTC, FerroEduardo commented on src/3-Basico/09-Estruturas de Decisões.md
> +    int n1=10, n2=3, maior=0; // Introduzimos o maior porque, conforme outros números superior a 0 apareçam, eles irão ser análisados pela estrutura de decisão.
Adicionar espaço entre `=` e valores/variáveis para manter o padrão. O mesmo vale para outras partes do arquivo

2022-10-15 00:35 UTC, FerroEduardo commented on src/3-Basico/09-Estruturas de Decisões.md
> +        maior = n1; // Se a variável for maior, o programa irá acessar as chaves do IF e ler o trecho do código que está dentro dele, neste caso, irá atribuir o valor da variável n1 para a variável m
Dividir o comentário em várias linhas, em vez de uma linha enorme. Só essa linha tem ~200 caracteres de comentário

2022-10-15 00:35 UTC, FerroEduardo commented on src/3-Basico/09-Estruturas de Decisões.md
> +A estrutura de decisão **ELSE IF** funciona igualmente a um IF, carregando uma condição entre os seus parenteses, diferentemente do ELSE, que caso o IF não seja verdadeiro, ele automaticamente é aces
Não fica claro que é possível ter mais de um `else if`

2022-10-15 00:35 UTC, FerroEduardo commented on src/3-Basico/09-Estruturas de Decisões.md
> +Ou seja, daremos uma condição e introduziremos um sinal de interrogação (?) após a condição ser apresentada. Esse sinal de interrogação funciona como um IF. **Se a condição for verdadeira**, o bloco
Não fica claro que o operador também retorna valores e é possível utilizar para atribuição

2022-10-15 00:35 UTC, FerroEduardo commented on src/3-Basico/09-Estruturas de Decisões.md
> +A estrutura de decisão IF *(se, em inglês)* pode ser utilizada para verificar qual número é o maior, por exemplo. Você sempre deve atribuir uma condição dentro das chaves do IF, para que a condição p
Apenas o `if` possui essa tradução, seria legal adicionar no `else` e `else if`

2022-10-15 00:35 UTC, FerroEduardo commented on README.MD
> +- **Vinícius Gonçalves Basílio** - _Developer & Member of He4rt Developers_ - [Github](https://github.com/vbasilioo)
Não vejo necessidade de adicionar essa informação, todos os contribuidores ficam visíveis [aqui](https://github.com/jpaulohe4rt/c4noobs/graphs/contributors)

2022-10-15 02:36 UTC, vbasilioo commented
Alterações já realizadas.

2022-10-19 01:09 UTC, FerroEduardo requested changes
Só precisa dessa correção

1. Apesar de ter dividido os comentários em várias linhas, ficou meio esquisito.   
    - Troca para algo assim:
        ```c
        // Lorem ipsum dolor sit amet, consectetur adipiscing elit
        int valor = 2;

        /*
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
        do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
        nisi ut aliquip ex ea commodo consequat.
        */
        int outroValor = 10

        // Lorem ipsum dolor sit amet
        if (condicao) {
            ...
        } else { // Lorem ipsum dolor sit amet
            ...
        }
        ```

2022-10-24 22:30 UTC, vbasilioo commented
Alterado, @FerroEduardo!

2022-11-03 13:21 UTC, FerroEduardo approved these changes

2022-11-03 13:44 UTC, merged

2022-11-03 13:44 UTC, jpaulohe4rt commented
Obrigado pela contribuição @vbasilioo @FerroEduardo 💜